language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
before_install:
  - gem install bundler
gemfile:
  - gemfiles/Gemfile-4-0
  - gemfiles/Gemfile-4-1
  - gemfiles/Gemfile-4-2
  - gemfiles/Gemfile-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-edge
    - rvm: 2.2
