language: ruby
rvm:
  - 2.5.5
  - 2.6.3
  - 2.7.0
gemfile:
  # - gemfiles/Gemfile-5-2
  - gemfiles/Gemfile-6-0
  - gemfiles/Gemfile-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-edge
script:
  - bundle exec rake test
  - bundle exec rubocop
